version: "3.8"

services:
    landing:
        image: nginx:latest
        container_name: synteny-explorer
        networks:
          - infovisnet
        volumes:
            - ./public:/usr/share/nginx/html

networks:
  infovisnet:
    name: infovisnet
